spring:
  datasource:
    url: jdbc:h2:file:./data/kenect-spring-test1-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: create
